Repository BrightCoders-Institute/BCDIC22-RN-proyecto-final-team2, pull requests merged in 2023-03, with the labels that each got.

#15 feature#11-Home screen design
  package-lock.json
  package.json
  src/components/CarouselSlider.jsx
  src/components/ProductCard.jsx
  src/navigation/index.jsx
  src/screens/Home.jsx
  src/styles/HomeScreen/Components_CarouselSlider.jsx
  src/styles/HomeScreen/Components_ProductCard.jsx
  src/styles/HomeScreen/Screen_Home.jsx
Labels: @garzo94

#16 frontend-backend-connection
  package-lock.json
  package.json
  src/components/LoginForm.jsx
  src/components/Modals/ErrorModalLogin.jsx
  src/components/Modals/ErrorModalSignup.jsx
  src/components/Modals/SuccessSignup.jsx
  src/components/SignUpForm.jsx
  src/navigation/index.jsx
  src/screens/Login.jsx
  src/styles/Modals/errorModal.jsx
Labels: @garzo94

#9 Feature#5 bottom and top bars
  src/components/BottomBar.jsx
  src/components/TopBar.jsx
  src/navigation/index.jsx
  src/styles/Bars/Component_BottomBar.jsx
  src/styles/Bars/Component_TopBar.jsx
Labels: @garzo94

#20 feature#18-User profile screen
  package-lock.json
  package.json
  src/components/UserInfo.jsx
  src/components/UserPicData.jsx
  src/navigation/index.jsx
  src/screens/UserProfile.jsx
  src/styles/UserProfileScreen/Components_UserInfo.jsx
  src/styles/UserProfileScreen/Components_UserPicData.jsx
  src/styles/colors.jsx
Labels: @garzo94

#27 Categories franchise enpoint integration
  src/components/CategoriesCard.jsx
  src/components/ProductCard.jsx
  src/screens/Categories/Categories.jsx
  src/screens/Categories/Franchises.jsx
  src/styles/CategoriesScreen/Screen_Categories.jsx
  src/styles/FranchisesScreen/Screen_Franchises.jsx
Labels: @HenrikhWolf

#30 First Checkout Screen
  package-lock.json
  package.json
  src/navigation/index.jsx
  src/resources/checkoutNavigator.png
  src/screens/Checkout.jsx
  src/styles/CheckoutScreen/Screen_Checkout.jsx
  src/styles/LoginScreen/Screen_Login.jsx
  src/styles/colors.jsx
Labels: @HenrikhWolf

#32 Navigation flux and bars
  package-lock.json
  package.json
  src/components/BottomBar.jsx
  src/components/CarouselSlider.jsx
  src/components/ProductCard.jsx
  src/components/SearchInput.jsx
  src/components/TopBar.jsx
  src/navigation/index.jsx
  src/navigation/loggedNav.jsx
  src/navigation/notLoggedNav.jsx
  src/navigation/onCategories.jsx
  src/navigation/onCheckout.jsx
  src/navigation/onHome.jsx
  src/screens/Categories/Categories.jsx
  src/screens/Categories/Franchises.jsx
  src/screens/Checkout.jsx
  src/screens/Greeting.jsx
  src/screens/Home.jsx
  src/screens/Login.jsx
  src/screens/UserProfile.jsx
  src/styles/Bars/Component_BottomBar.jsx
  src/styles/Bars/Component_TopBar.jsx
  src/styles/CategoriesScreen/Screen_Categories.jsx
  src/styles/CheckoutScreen/Screen_Checkout.jsx
  src/styles/FranchisesScreen/Screen_Franchises.jsx
  src/styles/FranchisesScreen/listItems.jsx
  src/styles/HomeScreen/Components_SearchInput.jsx
  src/styles/HomeScreen/Screen_Home.jsx
  src/styles/LoginScreen/Screen_Login.jsx
  src/styles/UserProfileScreen/Components_UserInfo.jsx
  src/styles/colors.jsx
  src/theme/themes.js
Labels: @Manz1999

#36 Cart screen
  package-lock.json
  package.json
  src/components/ItemCart.jsx
  src/navigation/index.jsx
  src/navigation/loggedNav.jsx
  src/navigation/onCategories.jsx
  src/navigation/onHome.jsx
  src/screens/Cart.jsx
  src/styles/CartScreen/Components_ItemCart.jsx
  src/styles/CartScreen/Screen_Cart.jsx
  src/styles/HomeScreen/Components_ProductCard.jsx
Labels: @Manz1999

#35 Second Checkout Screen
  App.js
  src/components/ProductCard.jsx
  src/navigation/index.jsx
  src/resources/checkoutNavigator2.png
  src/screens/Checkout/Checkout1.jsx
  src/screens/Checkout/Checkout2.jsx
  src/styles/CheckoutScreen/Screen_Checkout2.jsx
Labels: @Manz1999

#39 Fixed minor changes and resolved conflicts
  src/components/ProductCard.jsx
  src/navigation/index.jsx
  src/navigation/loggedNav.jsx
  src/screens/Checkout/Checkout1.jsx
  src/screens/Checkout/Checkout2.jsx
  src/styles/CheckoutScreen/Screen_Checkout.jsx
  src/styles/CheckoutScreen/Screen_Checkout2.jsx
Labels: @Manz1999

#33 Feature#25 wishlist screen
  src/components/WishedCard.jsx
  src/navigation/loggedNav.jsx
  src/navigation/onWishlist.jsx
  src/screens/Categories/WishList.jsx
  src/styles/HomeScreen/Components_ProductCard.jsx
  src/styles/WishlistScreen/Screen_Wishlist.jsx
  src/styles/WishlistScreen/listItems.jsx
  src/styles/colors.jsx
Labels: @Manz1999

#44 Navigation flux to Cart Screen to Checkout Screens
  src/navigation/loggedNav.jsx
  src/navigation/onCart.jsx
Labels: @QuackDuster
